# Generated by Django 2.1.7 on 2019-05-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0002_list_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateField(blank=True),
        ),
    ]
