# Generated by Django 2.1.7 on 2019-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0003_auto_20190520_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
