# Generated by Django 2.1.7 on 2019-05-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0005_auto_20190520_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='degree',
            field=models.IntegerField(choices=[(1, 'Not Urgent'), (2, 'Intermediate'), (3, 'Urgent')], default=1),
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
