# Generated by Django 2.1.7 on 2019-05-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0006_auto_20190520_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='degree',
            field=models.IntegerField(),
        ),
    ]
