# Generated by Django 2.1.7 on 2019-05-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listpage', '0008_auto_20190520_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='list',
            name='degree',
            field=models.IntegerField(choices=[(1, 'Very Urgent'), (2, 'Intermediate'), (3, 'Not Urgent')], default=1),
        ),
    ]
